### ISSUE TITLE
Table statistics missed from HTML runnig pgcluu with -b, -e options

### ISSUE THREAD

**Issue by jrohlicek-bsc** [darold/pgcluu#115]
Hello,
I installed pgcluu version 3.1, run in deamon mode for 2 days (then killed).
Generating HTML reports witch pgcluu with no time options, all statistics are generated.
When I use time window pgcluu options -b, -e
`# pgcluu -b 2020-02-11\ 18:00:00 -e "2020-02-11 19:00:00" \`
`   -o /var/lib/pgcluu/report/20200211_1800-1900/ /tmp/stat_pg_refdb/`
The table statistics in Databases-<dbname>-Database Info are zero and the option Databases-<dbname>-Table Statiscs is greyed off.
Do I something wrong?

In the report directory are missing files:
`cluster-settings.html`
`cluster-nondefault-settings.html`
`database-queries-<dbname>.html`
`<dbname>-index-size.html`
`<dbname>-table-size.html`

Regards,
Jiri Rohlicek

**Comment by darold** [comment]
Hi, thanks for the report.

Obviously time options are broken and worst it can not works correctly with different timezone on PG and system/sar. I think that trying to fix that will be a waste of time and I really think I will remove these options in next release. Best is to use the incremental mode in hourly rotation with pgcluu_collectd.
```
 -R, --rotate-hourly      force hourly rotation of data files.
```
or the CGI mode where you can choose exactly the time period you want to view.

With hourly rotation here will be a sub directory per hour of collected stats, for example in your case `/tmp/stat_pg_refdb/2020/02/11/18` then pgcluu  will build individual reports per hours using `pgcluu -o /var/lib/pgcluu/report/20200211_1800-1900/ /tmp/stat_pg_refdb/`

**Comment by jrohlicek-bsc** [comment]
Hi, thanks for the response. I will do as you suggested.

**Comment by jrohlicek-bsc** [comment]
Hi,
I started daemon pgcluu_collectd with --rotate-hourly, it runs well, creates and fills subdirectories per hour.
But now I am not able to create HTML output, pgcluu complains
`# pgcluu -o /var/lib/pgcluu/report/vtb/ /mnt/bsc/pgcluu/vtbdb/`
`LOG: Setting retention from configuration file to 10`
`WARNING: No sar data file found. Consider using -S or --disable-sar command`
`line option or use -i / -I option to set the path to the data file.`
`Continuing normally without reporting sar statistics.`
`FATAL: can't read file /mnt/bsc/pgcluu/vtbdb/2020/02/13/15/end-pg_stat_all_indexes.csv: No such file or directory`
There are no end_*,csv files in the whole /mnt/bsc/pgcluu/vtbdb/ directory structure.
Maybe they will appear at the end of the day and pgcluu wil run then?

Regards,
Jiri Rohlicek

**Comment by darold** [comment]
Please download and install latest development code and restart pgcluu_collectd this problem have been fixed.

**Comment by jrohlicek-bsc** [comment]
OK

**Comment by jrohlicek-bsc** [comment]
Unistalled
`yum erase pgcluu`
Downloaded last version here
`https://github.com/darold/pgcluu/archive/v3.1.tar.gz`
installed and run pgcluu_collectd. But still the same.

**Comment by darold** [comment]
Sorry I should give you the link, latest development code at https://github.com/darold/pgcluu/archive/master.zip

**Comment by jrohlicek-bsc** [comment]
OK, thanks.

**Comment by jrohlicek-bsc** [comment]
Still the same. pgcluu fails with error as pgcluu_collectd  creates no end-*csv files in the stat directory.
Strange is that the same problem is on other server, where I installed pgcluu v3.1 yesterday.
First I started it without --rotate-hourly, it created end-*csv files in the stat directory and pgcluu generated HTML reports.
Then I ran pgcluu_collectd with --rotate-hourly and from this on even pgcluu_collectd without --rotate-hourly does not create end-*csv files and pgcluu creates no reports from new stat directory.
I will try fresh install pgcluu on some other server and test without --rotate-hourly.

**Comment by darold** [comment]
Manual install `make install` copy pgcluu_collectd and pgcluu in `/usr/local/bin` you might want to override the possible previous installation in `/usr/bin/`. If this is the case just move the script in `/usr/bin`

**Comment by darold** [comment]
Hum, after more thougth does the `/mnt/bsc/pgcluu/vtbdb/` directory contains old data? If this is the case they might not be compatible. If there is no file named like bellow pgcluu will throw an error:
```
end-pg_statio_user_indexes.csv
end-pg_statio_user_sequences.csv
end-pg_statio_user_tables.csv
end-pg_stat_user_functions.csv
end-pg_stat_user_indexes.csv
end-pg_stat_user_tables.csv
end-pg_stat_xact_user_functions.csv
end-pg_stat_xact_user_tables.csv 
```

**Comment by jrohlicek-bsc** [comment]
Fresh install on Fedora release  30 NB pgcluu-3.1-2.f30.noarch, run as no daemon, works fine, creates end-pg*.csv files, pgcluu does not complain creating reports.
Something was wrong with my previous installation.

**Comment by darold** [comment]
Good news.
