### ISSUE TITLE
pgcluu_collectd fails if the output_dir contains spaces

### ISSUE THREAD

**Issue by Krysztophe** [darold/pgcluu#138]
I know, this is not a good idea, but theses things happen:

```bash
$ /opt/pgcluu/pgcluu_collectd   -v  --pid-file='/tmp/p i d/pgcluu collectd.pid'  "/tmp/aa bb/toto tutu"
LOG: Setting retention from configuration file to 30

*** pgcluu_collectd v3.2 (pid:1645445) started at Tue Feb  1 17:37:29 2022
Type Ctrl+c to quit.

grep: bb/toto: Aucun fichier ou dossier de ce type
grep: tutu/sar_stats.dat: Aucun fichier ou dossier de ce typegrep: bb/toto
: Aucun fichier ou dossier de ce type
grep: tutu/pidstat_stats.dat: Aucun fichier ou dossier de ce type
^CLOG: Received terminating signal INT.
```

This seems to work for the pid-file.

There are so many things to check that I gave up a real patch to correct it. Is it really worth it?
I'll do a quick PR to add a clean error.

**Comment by Krysztophe** [comment]
Details:

* Fails on Ubuntu (pgcluu master branch)
* Fails on CentOS (pgCluu RPM)

* It fails with `-S` too:

```
psql:<stdin>:42: erreur : n'a pas pu écrire les données du COPY : Relais brisé (pipe)
cat: bb/toto: Aucun fichier ou dossier de ce type
cat: tutu/pg_stat_locks.csv: Aucun fichier ou dossier de ce type
```

**Comment by ng-pe** [comment]
Hello Krysztophe

I think the problem is in :
`
\\cat $FILE_REDIR $OUT_DIR/$file_output
`
Should we add single quotes?

`
\o | cat '$FILE_REDIR' '$OUT_DIR/$file_output'
`
regards,

**Comment by Krysztophe** [comment]
as a real patch is WIP, I'm removing this PR

**Comment by Krysztophe** [comment]
@ng-pe :  Last results from you branch:  there is still a problem while copying the *.conf files, around line 1087.

**Comment by ng-pe** [comment]
Fixed whith other :
https://github.com/ng-pe/pgcluu/commits/fix-138

**Comment by Krysztophe** [comment]
@ng-pe : OK for a local execution

Still KO for an ssh access ; I'm looking...

**Comment by Krysztophe** [comment]
My mistake, that seems to work through ssh too.

I've found there is still a problem in System/Devices when a device has a space in it, as `//mafreebox.freebox.fr/Disque dur`, the report is lost, but I don't think that it matters in real life :smile:

**Comment by ng-pe** [comment]
WIP : https://github.com/ng-pe/pgcluu/commit/32216d9cb16b0383c323c63876908e87614f4fef 
Add fix in pgcluu.
