### ISSUE TITLE
Failed to show cgi report , cgi-error Use of uninitialized value $stats{"global_infos"} in hash dereference at /var/www/cgi-bin/pgcluu.cgi line 11920

### ISSUE THREAD

**Issue by lgj101** [darold/pgcluu#159]
The installation steps follow the official comments of #157 , but the report page cannot be displayed now. The error is shown in the figure below. Why?

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/29968308/204183065-892f902e-1015-404c-abec-02bbccdcc351.png">

Also, if the line below is not commented out, an error will be reported. Why? Hope to get your answer, thank you
![image](https://user-images.githubusercontent.com/29968308/204183196-0cef187e-4451-4583-b644-2bcecb764912.png)

**Comment by darold** [comment]
Latest commits should fix the uninitialized issue as well as a bug in pgcluu_collectd, please upgrade to latest development code and restart pgcluu_collectd.

For the second issue can you please report the error and you Apache version.

**Comment by lgj101** [comment]
I now run it with the code on the main branch. These codes are installed step by step. The execution results are as follows:

`/usr/local/bin/pgcluu_collectd  -i 30 -I /var/lib/pgcluu/data/  -h addr.1.1.1 -U postgres -W 123456 -p5432 -d postgres   /var/lib/pgcluu/data  --disable-sar
`
![Uploading 企业微信截图_5c478f63-bf1a-4ce2-ae95-c3558b208d28.png…]()

I found that the 'end *. csv' file was not generated. Why?


The second question raised above, my Apache version is as follows:
<img width="375" alt="企业微信截图_48637e10-ed90-43eb-9b54-13f52a34e1b1" src="https://user-images.githubusercontent.com/29968308/204430597-9052c194-66c5-41b8-9d54-de2f2f54a3bb.png">

error image:

<img width="1397" alt="企业微信截图_2f8ead4b-a9eb-48b8-ab7c-dd20e1beea22" src="https://user-images.githubusercontent.com/29968308/204430978-713dd527-b23d-4575-84ea-4c1aa36d6b38.png">

**Comment by lgj101** [comment]
I reinstalled it the way you said, 'end * The csv 'file can be generated, but the following error still exists. Why? Thank you for your answer.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/29968308/204490312-c3623300-8f00-49ef-805b-264c1a8b99c7.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/29968308/204490418-f0841fa7-dadc-4224-a72d-998a03131b79.png">

**Comment by darold** [comment]
I think the problem is that the CGI have been installed elsewhere like /usr/local/lib/cgi-bin/pgcluu.cgi , you might need to override the /var/www/cgi-bin/pgluu.cgi by this one or use a symlink.

You also don't have the resources file (css+js) at the right place, this is why you have raw html output.

On my Ubuntu host I have done the following after the instal to have everything working correctly:
```l 
sudo ln -s /usr/local/lib/cgi-bin/pgcluu.cgi /usr/lib/cgi-bin/pgcluu.cgi
sudo ln -s /usr/local/share/pgcluu /var/www/html/pgcluu
```
on your host it should probably be:
```
sudo ln -s /usr/local/lib/cgi-bin/pgcluu.cgi /var/www/cgi-bin/pgcluu.cgi
sudo ln -s /usr/local/share/pgcluu /var/www/html/pgcluu
```

**Comment by lgj101** [comment]
Thank you for your answer. It's OK now
